//#pragma once
////COMMON
//#define	SAFE_TIME	50
//#define	STORING_LOCATION_X	-100
//#define	STORING_LOCATION_Y	3000
//#define	ONE_LV_UP	0
//#define	GOOMBA_VALUE	100
//#define	MOVING_COIN_VALUE	100
//#define	KOOPAS_VALUE	100
//#define	MERANG_VALUE	1000
//#define	CONTROL_LOSE_ALL	-2
//#define	RIGHT_DIRECTIOM	1
//#define	LEFT_DIRECTIOM	-1
////Bell
//#define BELL_BBOX_WIDTH		16
//#define BELL_BBOX_HEIGHT	16
//
//#define BELL_DIE_BBOX_WIDTH		16
//#define BELL_DIE_BBOX_HEIGHT	7
//
//#define BELL_STATE_IDLE		0
//#define BELL_STATE_UP		100
//#define BELL_STATE_DIE		200
//
//
//#define BELL_ANI_ALIVE		0
//#define BELL_ANI_DIE		1
//
//
//
//#define BELL_STATE_DIE_TOP_BBOX		9
//#define BELL_STATE_UP_TIME_UP		100
//#define BELL_STATE_IDLE_SPEED_IDLE	0
//#define BELL_STATE_UP_SPEED_UP		0.1f
//
////Coin
//#define COIN_BBOX_WIDTH  10
//#define COIN_BBOX_HEIGHT 15
//
//
//#define COIN_STATE_IDLE		0
//#define COIN_STATE_UP		100
//#define COIN_STATE_DOWN		200
//
//#define COIN_NORMAL			222
//#define COIN_CAN_MOVE		333
//
////FỉeBall
//#define FIREBALL_SPEED 0.15f;
//
//#define FIREBALL_BBOX_WIDTH	7
//#define FIREBALL_BBOX_HEIGHT 9
//
//#define	FIREBALL_STATE_DIE	90
//#define FIREBALL_STATE_FLYING 100
//
//
//#define FIREBALL_ANI_FLYING 0
//
//#define FIREBALL_GRAVITY	0.0008f
//#define FIREBALL_RESET_TIME 5000
//
////Flower
//#define FLOWER_RED_BBOX_WIDTH  16
//#define FLOWER_RED_BBOX_HEIGHT 32
//
//#define FLOWER_GREEN_BBOX_WIDTH  16
//#define FLOWER_GREEN_BBOX_HEIGHT 24
//
//#define FLOWER_GREEN_CAN_SHOOT_BBOX_WIDTH  16
//#define FLOWER_GREEN_CAN_SHOOT_BBOX_HEIGHT 24
//
//#define FLOWER_RED_ANI_LEFT			0
//#define FLOWER_RED_ANI_RIGHT		1
//#define FLOWER_RED_ANI_LEFT_IDLE	2
//#define FLOWER_RED_ANI_RIGHT_IDLE	3
//#define FLOWER_GREEN_ANI			4
//#define FLOWER_GREEN_CAN_SHOOT_ANI_LEFT			5
//#define FLOWER_GREEN_CAN_SHOOT_ANI_RIGHT		6
//#define FLOWER_GREEN_CAN_SHOOT_ANI_LEFT_IDLE	7
//#define FLOWER_GREEN_CAN_SHOOT_ANI_RIGHT_IDLE	8
//#define FLOWER_RED_ANI_LEFT_UP						9
//#define FLOWER_RED_ANI_RIGHT_UP						10
//#define FLOWER_RED_ANI_LEFT_IDLE_UP					11
//#define FLOWER_RED_ANI_RIGHT_IDLE_UP				12
//#define FLOWER_GREEN_CAN_SHOOT_ANI_LEFT_UP			13
//#define FLOWER_GREEN_CAN_SHOOT_ANI_RIGHT_UP			14
//#define FLOWER_GREEN_CAN_SHOOT_ANI_LEFT_IDLE_UP		15
//#define FLOWER_GREEN_CAN_SHOOT_ANI_RIGHT_IDLE_UP	16
//
//#define FLOWER_RED				100
//#define FLOWER_GREEN			200
//#define FLOWER_GREEN_CAN_SHOOT  300 
//
//
//#define FLOWER_RED_TOP_LIMIT			336
//#define FLOWER_RED_BOT_LIMIT			384
//#define TIME_SHOWING_LIMIT				3000
//
//#define FLOWER_GREEN_TOP_LIMIT			361
//#define FLOWER_GREEN_BOT_LIMIT			391
//#define GREEN_TIME_SHOWING_LIMIT		2000
//
//
//#define FLOWER_GREEN_CAN_SHOOT_TOP_LIMIT		344
//#define FLOWER_GREEN_CAN_SHOOT_BOT_LIMIT		391
//
//
//#define FLOWER_ORIGIN_SPEED					0
//#define FLOWER_ALLOW_UP_DISTANCE_X			40
//#define FLOWER_ALLOW_UP_DISTANCE_Y			70
//#define FLOWER_TIME_SHOWING_ORIGIN_VALUE	0
//#define FLOWER_SPEED_UP				0.02f
//#define FLOWER_SPEED_IDLE			0
//#define FLOWER_TIME_ALLOW_TO_FIRE	2900
//
////Flower Bullet
//#define FLOWER_BULLET_BBOX_WIDTH  8
//#define FLOWER_BULLET_BBOX_HEIGHT 9
//
//#define FLOWER_BULLET_X_LIMIT		72
//
//
//#define FLOWER_BULLET_FLYING_SPEED		0.05f 
//
//#define FLOWER_BULLET_STATE_FLYING		100
//#define FLOWER_BULLET_STATE_HIDDEN		200
//
//#define FLOWER_BULLET_ANI			0
//
////Game
//#define DIRECTINPUT_VERSION 0x0800
//#define KEYBOARD_BUFFER_SIZE 1024
//#define	TIME_VALUE	50
//
////GameObject
//#define ID_TEX_BBOX -100		// special texture to draw object bounding box
//
////KOOPAS
//#define KOOPAS_WALKING_SPEED 0.05f;
//#define KOOPAS_SPINNING_SPEED 0.3f;
//
//#define KOOPAS_DEFLECT_SPEED_Y	-0.4f
//#define KOOPAS_DEFLECT_SPEED_X	0.21f
//
//#define KOOPAS_BBOX_WIDTH 15
//#define KOOPAS_BBOX_HEIGHT 26
//#define KOOPAS_BBOX_HEIGHT_SHELL 15
//
//#define KOOPAS_STATE_WALKING 100
//#define KOOPAS_STATE_SHELLING	120
//#define KOOPAS_STATE_SPINNING	125
//#define KOOPAS_STATE_SHELL_UP	130
//#define KOOPAS_STATE_SHELL_DOWN 140
//#define KOOPAS_STATE_FLYING_UP_DOWN	150
//#define KOOPAS_STATE_DIE		1
//#define KOOPAS_STATE_DIE_2		2
//
//#define KOOPAS_ANI_WALKING_LEFT		0
//#define KOOPAS_ANI_WALKING_RIGHT	1
//#define KOOPAS_ANI_FLYING_LEFT		2
//#define KOOPAS_ANI_SHELL_DOWN		3
//#define KOOPAS_ANI_SHELL_UP			4
//#define KOOPAS_RED_ANI_WALKING_LEFT 5
//#define KOOPAS_RED_ANI_WALKING_RIGHT 6
//#define KOOPAS_RED_ANI_FLYING_LEFT	7
//#define KOOPAS_RED_ANI_SHELL_DOWN	8
//#define KOOPAS_ANI_SPINNING			9
//#define KOOPAS_RED_ANI_SPINNING		10
//#define KOOPAS_XANH_ANI_REVIVING	  11
//#define KOOPAS_RED_ANI_REVIVING		  12
//#define KOOPAS_RED_ANI_SHELL_UP	  13
//#define KOOPAS_XANH_ANI_REVIVING_NGUA	14
//#define KOOPAS_RED_ANI_REVIVING_NGUA	15
//#define KOOPAS_BLACK_UP							16
//#define KOOPAS_BLACK_NGUA						17
//#define KOOPAS_XANH_ANI_WALKING_RIGHT_FASTER	18
//#define KOOPAS_ANI_SPINNING_UP		19
//#define KOOPAS_RED_ANI_SPINNING_UP		20
//#define KOOPAS_RED_ANI_FLYING_LEFT_NEW			21
//
//#define KOOPAS_GRAVITY	0.002f
//
//#define KOOPAS_JUMP_SPEED		0.35f
//#define KOOPAS_TIME_JUMPING		900
//
//#define KOOPAS_XANH_WALK	111
//#define KOOPAS_XANH_FLY		222
//#define KOOPAS_RED_WALK		333
//#define KOOPAS_BLACK		444
//
//#define KOOPAS_SHELL_VX			0.1f
//#define KOOPAS_JUMP_SPEED_VX	1.5f
//#define SWITCHING_STATE_TIME	2000
//#define SWITCHING_STATE_TIME_ORIGIN_VALUE	0
//#define KOOPAS_STATE_FLYING_UP_DOWN_VY		0.06f
//#define KOOPAS_SHELL_DEFLECT_SPEED_VX		0.04f
//#define REVIVE_START_TIME			5000
//#define REVIVE_START_X				5
//#define REVIVE_START_Y				10
//#define REVIVE_START_TIME_2			3000
//#define KOOPAS_SET_POSITION			21000
//#define KOOPAS_IS_HOLDING_X			1
//#define KOOPAS_IS_HOLDING_Y			10
//#define KOOPAS_IS_HOLDING_Y_2		8
//#define MARIO_LEVEL_SMALL_KOOPAS_BONUS_Y	10
//#define MARIO_LEVEL_TAIL_KOOPAS_BONUS_X		15
//#define TIMINGSUBRECWIDTH			300
//#define KOOPAS_CHECK_POSITION_MINUS_Y		5.0f
//#define KOOPAS_CHECK_POSITION_BONUS_X		12.0f
//#define KOOPAS_RESET_SPINNING_LIMIT_X			315
//#define KOOPAS_RESET_SPINNING_SET_POSITION_X	30
//#define KOOPAS_RESET_SPINNING_SET_POSITION_Y	117
//#define KOOPAS_STATE_DIE_VX				0.1f
//#define KOOPAS_STATE_SHELL_IDLE_SPEED			0
//
////LEAF
//#define LEAF_BBOX_WIDTH		16
//#define LEAF_BBOX_HEIGHT	14
//
//#define LEAF_STATE_IDLE		0
//#define LEAF_STATE_UP		100
//#define LEAF_STATE_DOWN		200
//
//
//
//#define LEAF_ANI_LEFT		0
//#define LEAF_ANI_RIGHT		1
//
//
//#define COLLI_TIME_TAIL_ORIGIN_VALUE	0
//#define LEAF_UPPING_START_TIME_1		500
//#define	LEAF_UPPING_START_TIME_2		1500
//#define LEAF_DOWNING_START_TIME_ORIGIN_VALUE	0
//#define LEAF_DOWNING_START_TIME		500
//#define LEAF_SET_POSITION			5000
//#define COLLI_TIME_TAIL				400
//#define LEAF_STATE_IDLE_SPEED		0				
//#define LEAF_STATE_UP_SPEED			0.04f
//#define LEAF_STATE_DOWN_VX          0.04f
//#define LEAF_STATE_DOWN_VY			0.035f
//
////MUSHROOM
//#define MUSHROOM_BBOX_WIDTH		16
//#define MUSHROOM_BBOX_HEIGHT	16
//
//#define MUSHROOM_STATE_IDLE		0
//#define MUSHROOM_STATE_UP		100
//#define MUSHROOM_STATE_MOVE		200
//
//#define MUSHROOM_GRAVITY		0.002f
//#define MUSHROOM_RED			567
//#define MUSHROOM_GREEN			678
//
//#define MUSHROOM_ANI_RED		0
//#define MUSHROOM_ANI_GREEN		1
//
////NOCOLLISION OBJECT
//#define OBJECT_BBOX_WIDTH  16
//#define OBJECT_BBOX_HEIGHT 16
//
////PIPE
//#define RECT_BBOX_WIDTH  16
//#define RECT_BBOX_HEIGHT 16
//
////PLAY_SCENE
//
//#define NO_STATE 999999
//#define LOSE_ALL_CONTROL -2
//#define MAX_RENDER_LAYER 3
//#define CAM_START 0
//
//#define SCENE_SECTION_UNKNOWN -1
//#define SCENE_SECTION_TEXTURES 2
//#define SCENE_SECTION_SPRITES 3
//#define SCENE_SECTION_ANIMATIONS 4
//#define SCENE_SECTION_ANIMATION_SETS	5
//#define SCENE_SECTION_OBJECTS	6
//#define SCENE_SECTION_GRID	7
//
//#define SCENE_1_4_ID 4
//#define SCENE_1_1_ID 3
//#define	WORLD_MAP_ID	2
//#define	INTRO_SCENE_ID	1
//
//
//#define OBJECT_TYPE_MARIO				 0
//#define OBJECT_TYPE_BRICK				 1
//#define OBJECT_TYPE_GOOMBA_NORMAL		 2
//#define OBJECT_TYPE_KOOPAS_XANH_WALK	 3
//#define OBJECT_TYPE_NO_COLLISION_OBJECTS 4
//#define OBJECT_TYPE_RECTANGLE			 5
//#define OBJECT_TYPE_PIPE				 6
//#define OBJECT_TYPE_KOOPAS_XANH_BAY		 7 
//#define OBJECT_TYPE_KOOPAS_RED_WALK		 8
//#define OBJECT_TYPE_COIN_NORMAL			 10
//#define OBJECT_TYPE_GOOMBA_RED_FLY  11 
//#define OBJECT_TYPE_FIREBALL		12
//#define OBJECT_TYPE_FLOWER_RED		13
//#define OBJECT_TYPE_FLOWER_BULLET	14
//#define OBJECT_TYPE_COIN_CAN_MOVE	15
//#define OBJECT_TYPE_LEAF			16
//#define OBJECT_TYPE_MUSHROOM_RED		17
//#define OBJECT_TYPE_QUESTION_BRICK	18
//#define OBJECT_TYPE_MUSHROOM_GREEN		19
//#define OBJECT_TYPE_QUESTION_BRICK_HAVE_ITEM	20
//#define OBJECT_TYPE_FLOWER_GREEN				21
//#define OBJECT_TYPE_FLOWER_GREEN_CAN_SHOOT		22
//#define OBJECT_TYPE_BREAKABLE_BRICK				23
//#define OBJECT_TYPE_BELL						24
//
//#define OBJECT_TYPE_HUD_PANEL			25
//#define OBJECT_TYPE_MARIO_LUIGI			26
//#define OBJECT_TYPE_LIFE				27
//#define OBJECT_TYPE_MONEY				28
//#define OBJECT_TYPE_SCORE				29
//#define OBJECT_TYPE_TIME_PICKER			30
//#define OBJECT_TYPE_WORLD				31
//#define OBJECT_TYPE_STACK_NORMAL		32
//#define OBJECT_TYPE_STACK_MAX			33
//#define OBJECT_TYPE_ITEM				34
//
//#define OBJECT_TYPE_BLACK_BLACK			35
//#define OBJECT_TYPE_SPECIAL_ITEM		36
//
//#define OBJECT_TYPE_PIPE_DOWN			37
//#define OBJECT_TYPE_PIPE_UP				38
//#define OBJECT_TYPE_SCORE_AND_1LV		39
//
//#define OBJECT_TYPE_WORDS_END_SCENE_COURSE_CLEAR		40
//#define OBJECT_TYPE_WORDS_END_SCENE_YOU_GOT_A_CARD		41
//#define OBJECT_TYPE_WORDS_END_SCENE_ITEM				42
//#define OBJECT_TYPE_MOVING_ROCK		43
//
//#define OBJECT_TYPE_NEW_MAP_CAM 47
//#define OBJECT_TYPE_QUESTION_BRICK_HAVE_MULTIPLE_LIFE					48
//#define OBJECT_TYPE_MOVING_HORIZONTAL_RECTANGLE							49
//#define OBJECT_TYPE_BOOMERANG											50
//#define OBJECT_TYPE_BOOMERANG_ENEMY										51
//
//#define OBJECT_TYPE_KOOPAS_RED_FLY		52	
//
//#define KOOPAS_RED_FLY	777
//
//#define OBJECT_TYPE_FIRE_FLOWER											53
//
//#define OBJECT_TYPE_HIT_EFFECT_TURN_TAIL								54
//
//#define OBJECT_TYPE_HIT_EFFECT_FIRE_BULLET								55
//
//#define OBJECT_TYPE_PORTAL												56
//
//#define MOVE_CAM_X_VX 0.1f
//
//#define MAX_SCENE_LINE 1024
//
////GRID
//
//#define IN_USE_WIDTH 330
//#define IN_USE_HEIGHT 300
//#define CAM_X_BONUS 50
//
////WMAP
//#define SCENE_SECTION_MAP				8
//
////ScoreManager
//#define SCORE_FIX_PST_Y		10
//
////PORTAL
//#define PORTAL_WIDTH 30
//#define PORTAL_HEIGHT 30
//
////BOOMERANG
//#define STATE_1_DURATION	500
//#define BOOMERANG_VX_1		0.1f
//#define BOOMERANG_VY_1		0.00006f
//#define BOOMERANG_VY_2		0.00015f
//#define ALLOW_TO_HIT_TIME	250
//#define STATE_2_DURATION	1200
//#define STATE_3_DURATION	1600
//#define STATE_4_DURATION	4000
//#define ALLOW_TO_SHOT_TIME	250
//
//
////BOOMERANG ENEMY
//#define  BOOMERANG_ENEMY_LOOK_LEFT_LIMIT		-1
//#define  BOOMERANG_ENEMY_LOOK_RIGTH_LIMIT		18
//#define  BOOMERANG_ENEMY_BBOX_WIDTH		16
//#define  BOOMERANG_ENEMY_BBOX_HEIGHT	24
//
//#define  BOOMERANG_ENEMY_STATE_IDLE				0
//#define  BOOMERANG_ENEMY_STATE_MOVE_FORWARD		100
//#define  BOOMERANG_ENEMY_STATE_MOVE_BACKWARD    200
//#define	 BOOMERANG_ENEMY_STATE_DIE				300
//
//#define BOOMERANG_ENEMY_GRAVITY		0.002f
//
//#define BOOMERANG_ENEMY_ANI_NORMAL_RIGHT				0
//#define BOOMERANG_ENEMY_ANI_THROW_BOOMERANG_RIGHT		1
//#define BOOMERANG_ENEMY_ANI_DIE_RIGHT					2
//#define BOOMERANG_ENEMY_ANI_DIE_LEFT					3
//#define BOOMERANG_ENEMY_ANI_NORMAL_LEFT					4	
//#define BOOMERANG_ENEMY_ANI_THROW_BOOMERANG_LEFT		5
//#define	RENDER_THROW_ANI_TIME_LIMIT		300
//#define	RENDER_THROW_TIME_LIMIT		900
//#define	RENDER_SECOND_THROW_TIME_LIMIT	3300
//#define	BOOMETANG_ENEMY_STATE_MOVE_FORWARD_LIMIT	700
//#define	BOOMETANG_ENEMY_STATE_IDLE_LIMIT	2000
//#define	BOOMETANG_ENEMY_STATE_MOVE_BACKWARD_LIMIT	2700
//#define	BOOMETANG_ENEMY_STATE_IDLE_2_LIMIT	4000
//#define	BOOMETANG_ENEMY_VX	0.03f
//#define	BOOMETANG_ENEMY_VY	0
//
////BREAKABLE_BRICK
//
//#define BREAKABLE_BRICK_BBOX_WIDTH		16
//#define BREAKABLE_BRICK_BBOX_HEIGHT		16
//
//#define BREAKABLE_BRICK_STATE_NORMAL	0
//#define BREAKABLE_BRICK_STATE_BREAK		100
//#define BREAKABLE_BRICK_STATE_COIN		200
//#define BREAKABLE_BRICK_STATE_SLIDING	300
//
//#define BREAKABLE_BRICK_ANI_NORMAL		0
//#define BREAKABLE_BRICK_ANI_COIN		1
//
//#define	BREABLE_BRICK_REVIVE_TIME 			5000
//#define	BREABLE_BRICK_MOVE_LIMIT			4
//#define	BREABLE_BRICK_MOVE_SPEED			2
//#define	BREABLE_BRICK			0
//
////Brick
//#define BRICK_BBOX_WIDTH  16
//#define BRICK_BBOX_HEIGHT 16
//#define BRICK_INTRO_BBOX_WIDTH  256
//#define BRICK_INTRO_BBOX_HEIGHT 38
//
////FIRE BALL
//#define	FIRE_BALL_SPEED_VX	0.1f
//#define	FIRE_BALL_SPEED_VY	0.1f
//#define	FIRE_BALL_STATE_DIE_VX	0
//#define	FIRE_BALLSTATE_DIE_VY 0
//
////MENU GAME
//#define MENU_GAME_ANI_1_PLAYER	0
//#define MENU_GAME_ANI_2_PLAYER	1
//
////MOVING_HORIZONTAL_RECTANGLE
//#define MOVING_HORIZONTAL_RECTANGLE_BBOX_WIDTH		48
//#define MOVING_HORIZONTAL_RECTANGLE_BBOX_HEIGHT		16
//#define  MOVING_HORIZONTAL_RECTANGLE_STATE_NORMAL		0
//#define  MOVING_HORIZONTAL_RECTANGLE_STATE_DOWN			100
//#define	 MOVING_HORIZONTAL_RECTANGLE_STATE_NORMAL_SPEED   -0.05f
//#define  MOVING_HORIZONTAL_RECTANGLE_STATE_DOWN_SPEED	   0.04f
//#define	MOVING_HORIZONTAL_RECTANGLE_FIX_Y_SMALL	27
//#define	MOVING_HORIZONTAL_RECTANGLE_FIX_Y	15
//
////MOVING_ROCK
//#define	MOVING_ROCK_DELAY_TIME_GRAVITY			100
//#define	MOVING_ROCK_PTS_FIX			8
//#define	MOVING_ROCK_DISAPEAR_TIME_LIMIT		1200
//#define	MOVING_ROCK_DELAY_TIME_MOVING		50
//#define	MOVING_ROCK_VX			0.08f
//#define	MOVING_ROCK_VY			0.08f
//#define	MOVING_ROCK_STATE_IDLE_VX		0
//#define	MOVING_ROCK_STATE_IDLE_VY	0
//
////MUSHROOM	
//#define	MUSHROOM_UP_TIME	300
//#define	MUSHROOM_STATE_IDLE_SPEED	0
//#define	MUSHROOM_STATE_MOVE_SPEED_VX	0.04f
//#define	MUSHROOM_STATE_MOVE_SPEED_VY	0.08f
//
////PIPE
//#define PIPE_BBOX_WIDTH  32
//#define PIPE_BBOX_HEIGHT 16
//
//#define PIPE_BBOX_FIX  1
//#define PIPE_BBOX_WIDTH_NORMAL	16
//
//
//#define PIPE_TYPE_NORMAL	100
//#define PIPE_TYPE_DOWN		200
//#define PIPE_TYPE_UP		300
//
//#define PIPING_LIMIT_LEFT	2
//#define PIPING_LIMIT_RIGHT	16
//
////QUESTION BRICK
//#define QUESTION_BRICK_BBOX_WIDTH  16
//#define QUESTION_BRICK_BBOX_HEIGHT 16
//
//
//
//#define QUESTION_BRICK_ANI_ALIVE	0
//#define QUESTION_BRICK_ANI_DEAD		1
//#define QUESTION_BRICK_ANI_NEW_TYPE	2
//
//
//#define QUESTION_BRICK_HAVE_LEAF			777
//#define QUESTION_BRICK_JUST_HAVE_MUSHROOM	888
//#define QUESTION_BRICK_HAVE_COIN_MULTIPLE_LIFE	999
//#define	QUESTION_BRICK_MAX_LIFE	10
//#define	QUESTION_BRICK_MIN_LIFE	0
//#define	QUESTION_BRICK_SLIDE_MAX_TIME	4
//#define	QUESTION_BRICK_STATE_IDLE_VY	0
//#define	QUESTION_BRICK_SLIDE_RANGE	2
//
////RECT
//#define RECTANGLE_BBOX_WIDTH  16
//#define RECTANGLE_BBOX_HEIGHT 16
//
////SCORE
//#define	SCORE_APPEAR_TIME	600
//#define	SCORE_STATE_IDLE_SPEED	0
//#define	SCORE_STATE_UP_SPEED	0.08f
//
////SCROLLINGSTAGE
//#define	SCROLLINGSTAGE_SHOW_UP_TIME	1000
//#define	SCROLLING_STAGE_STATE_IDLE_SPEED	0
//#define	SCROLLING_STAGE_STATE_UP_SPEED	0.1f
//
////SPECIAL_ITEM
//#define	SPECIAL_ITEM
//#define	SPECIAL_ITEM
//#define	SPECIAL_ITEM_STATE_STAR_IDLE_SPEED	0
//#define	SPECIAL_ITEM_STATE_STAR_UP_SPEED	0.09f
//
////STAR
//#define	STAR_SHOW_PST_LIMIT	300	
//#define	STAR_SPEED_VX	0.2f
//#define	STAR_SPEED_VY	0.4f
//#define	STAR_STATE_IDLE_SPEED	0
//
////WORDSENDSCENE
//#define	WORDSENDSCENE_CLEAR_SHOW_TIME	1000	
//#define	WORDSENDSCENE_GOT_A_CARD_SHOW_TIME	1500	
//#define	WORDSENDSCENE_ITEM_SHOW_TIME	2000	
//
////NODE
//#define	SEARCH_TOP	1
//#define	SEARCH_LEFT	4
//#define	SEARCH_RIGHT	3
//#define	SEARCH_BOTTOM	2
//#define	SCENE_1_4_NODE	8
//#define	SCENE_1_1_NODE	2
//#define	NODE_SEARCHING_RANGE	50
//
//
////WORLDMAPOBJECTS
//#define	WORLDMAPOBJECTS_GOLD_DIGGER_WALK_TIME_LIMIT	1500
//#define	WORLDMAPOBJECTS_HELP_SHOW_TIME_LIMIT	1000
//#define	WORLDMAPOBJECTS_MARIO_MOVE_TIME_LIMIT	200
//#define	WORLDMAPOBJECTS_RENDER_STAGE_OF_PROCESS_SHOW_TIME	50
//#define	WORLDMAPOBJECTS_RENDER_STAGE_OF_PROCESS_END_TIME	700
//#define	WORLDMAPOBJECTS_RENDER_MARIO_TIME	1500
//
////MARIO
//#define DIE_DEFLECT_SPEED_Y	-0.4f
//#define DIE_DEFLECT_SPEED_X	0.15f
//
//#define MARIO_WALKING_SPEED		0.12f 
//#define MARIO_WALKING_GIATOC	0.0005f
//
//#define MARIO_LOCK_LEFT	1
//#define MARIO_LOCK_RIGHT	-1
//
//#define MARIO_JUMP_HIGH_SPEED_Y	-0.68f
//#define MARIO_JUMP_SPEED_Y		0.2f
//#define MARIO_JUMP_DEFLECT_SPEED -0.34f
//#define MARIO_GRAVITY			0.002f
//#define MARIO_DIE_DEFLECT_SPEED	 0.5f
//#define MARIO_SPEED_DOWN		0.01f 
//#define MARIO_FALLING_DOWN_SPEED	0.04f
//#define MARIO_MAX_SPEED		0.38f 
//#define MARIO_MAX_SPEED_LEVEL	7
//#define MARIO_MIN_SPEED_LEVEL	0
//#define MARIO_ACCELERATE_SPEED	0.04f
//
//#define MARIO_STATE_IDLE			0
//#define MARIO_STATE_WALKING_RIGHT	100
//#define MARIO_STATE_WALKING_LEFT	101
//#define MARIO_STATE_JUMP			102
//#define MARIO_STATE_DIE				400
//#define MARIO_STATE_FLYING_RIGHT	500
//#define MARIO_STATE_FLYING_LEFT		600
//#define MARIO_STATE_BRAKING_RIGHT	700	
//#define MARIO_STATE_BRAKING_LEFT	800
//#define MARIO_STATE_HOLDING_RIGHT	900
//#define MARIO_STATE_HOLDING_LEFT	1000
//#define MARIO_STATE_HOLDING			1100
//#define MARIO_STATE_KICK			1200
//#define MARIO_STATE_RUNNING_RIGHT	110
//#define MARIO_STATE_RUNNING_LEFT	1400
//#define MARIO_STATE_SITDOWN			1500
//#define MARIO_STATE_LEVEL_CHANGING	1600
//#define MARIO_STATE_SPEED_DOWN		1700
//#define MARIO_STATE_FALLING_DOWN	1800
//#define MARIO_STATE_JUMP_HIGH		1900
//#define MARIO_STATE_HITTED			2000
//#define MARIO_STATE_LOOK_UP			2100
//#define MARIO_STATE_PIPE_DOWNING	2200
//#define MARIO_STATE_PIPE_UPPING		2300
//#define	MARIO_STATE_JUMPING_LONGER	2400
//
//
//
//#define MARIO_ANI_BIG_IDLE_RIGHT		0
//#define MARIO_ANI_BIG_IDLE_LEFT			1
//#define MARIO_ANI_BIG_WALKING_RIGHT		2	
//#define MARIO_ANI_BIG_WALKING_LEFT		3
//#define MARIO_ANI_BIG_JUMPING_RIGHT		4
//#define MARIO_ANI_BIG_JUMPING_LEFT		5
//#define MARIO_ANI_BIG_FLYING_RIGHT		6	
//#define MARIO_ANI_BIG_FLYING_LEFT		7
//#define MARIO_ANI_BIG_BRAKING_RIGHT		8	
//#define MARIO_ANI_BIG_BRAKING_LEFT		9
//#define MARIO_ANI_BIG_HOLDING_RIGHT		10	
//#define MARIO_ANI_BIG_HOLDING_LEFT		11
//#define MARIO_ANI_BIG_KICKING_RIGHT		12	
//#define MARIO_ANI_BIG_KICKING_LEFT		13
//#define MARIO_ANI_BIG_RUNNING_RIGHT		14	
//#define MARIO_ANI_BIG_RUNNING_LEFT		15
//#define MARIO_ANI_BIG_SITDOWN_RIGHT		16	
//#define MARIO_ANI_BIG_SITDOWN_LEFT		17
//#define MARIO_ANI_BIG_JUMP_FALLING_RIGHT	18
//#define MARIO_ANI_BIG_JUMP_FALLING_LEFT		19
//
//#define MARIO_ANI_SMALL_IDLE_RIGHT			20
//#define MARIO_ANI_SMALL_IDLE_LEFT			21
//#define MARIO_ANI_SMALL_WALKING_RIGHT		22	
//#define MARIO_ANI_SMALL_WALKING_LEFT		23
//#define MARIO_ANI_SMALL_JUMPING_RIGHT		24
//#define MARIO_ANI_SMALL_JUMPING_LEFT		25
//#define MARIO_ANI_SMALL_FLYING_RIGHT		26
//#define MARIO_ANI_SMALL_FLYING_LEFT			27
//#define MARIO_ANI_SMALL_BRAKING_RIGHT		28
//#define MARIO_ANI_SMALL_BRAKING_LEFT		29
//#define MARIO_ANI_SMALL_HOLDING_RIGHT		30
//#define MARIO_ANI_SMALL_HOLDING_LEFT		31
//#define MARIO_ANI_SMALL_KICKING_RIGHT		32
//#define MARIO_ANI_SMALL_KICKING_LEFT		33
//#define MARIO_ANI_SMALL_RUNNING_RIGHT		34	
//#define MARIO_ANI_SMALL_RUNNING_LEFT		35
//
//
//#define MARIO_ANI_TAIL_IDLE_RIGHT		40
//#define MARIO_ANI_TAIL_IDLE_LEFT		41
//#define MARIO_ANI_TAIL_WALKING_RIGHT	42
//#define MARIO_ANI_TAIL_WALKING_LEFT		43
//#define MARIO_ANI_TAIL_JUMPING_RIGHT	44
//#define MARIO_ANI_TAIL_JUMPING_LEFT		45
//#define MARIO_ANI_TAIL_FLYING_RIGHT		46	
//#define MARIO_ANI_TAIL_FLYING_LEFT		47
//#define MARIO_ANI_TAIL_BRAKING_RIGHT	48	
//#define MARIO_ANI_TAIL_BRAKING_LEFT		49
//#define MARIO_ANI_TAIL_HOLDING_RIGHT	50	
//#define MARIO_ANI_TAIL_HOLDING_LEFT		51
//#define MARIO_ANI_TAIL_KICKING_RIGHT	52	
//#define MARIO_ANI_TAIL_KICKING_LEFT		53
//#define MARIO_ANI_TAIL_RUNNING_RIGHT	54	
//#define MARIO_ANI_TAIL_RUNNING_LEFT		55
//#define MARIO_ANI_TAIL_SITDOWN_RIGHT	56
//#define MARIO_ANI_TAIL_SITDOWN_LEFT		57
//#define MARIO_ANI_TAIL_TURNING_LEFT		58
//#define MARIO_ANI_TAIL_TURNING_RIGHT	59
//#define MARIO_ANI_TAIL_JUMP_FALLING_RIGHT	60
//#define MARIO_ANI_TAIL_JUMP_FALLING_LEFT	61
//
//#define MARIO_ANI_FIRE_IDLE_RIGHT		62
//#define MARIO_ANI_FIRE_IDLE_LEFT		63
//#define MARIO_ANI_FIRE_WALKING_RIGHT	64	
//#define MARIO_ANI_FIRE_WALKING_LEFT		65
//#define MARIO_ANI_FIRE_JUMPING_RIGHT	66
//#define MARIO_ANI_FIRE_JUMPING_LEFT		67
//#define MARIO_ANI_FIRE_FLYING_RIGHT		68	
//#define MARIO_ANI_FIRE_FLYING_LEFT		69
//#define MARIO_ANI_FIRE_BRAKING_RIGHT	70	
//#define MARIO_ANI_FIRE_BRAKING_LEFT		71
//#define MARIO_ANI_FIRE_HOLDING_RIGHT	72
//#define MARIO_ANI_FIRE_HOLDING_LEFT		73
//#define MARIO_ANI_FIRE_KICKING_RIGHT	74	
//#define MARIO_ANI_FIRE_KICKING_LEFT		75
//#define MARIO_ANI_FIRE_RUNNING_RIGHT	76	
//#define MARIO_ANI_FIRE_RUNNING_LEFT		77
//#define MARIO_ANI_FIRE_SITDOWN_RIGHT	78
//#define MARIO_ANI_FIRE_SITDOWN_LEFT		79
//#define MARIO_ANI_SHOOTING_RIGHT		80
//#define MARIO_ANI_SHOOTING_LEFT			81
//#define MARIO_ANI_BIG_MAX_SPEED_RIGHT	82
//#define MARIO_ANI_BIG_MAX_SPEED_LEFT	83
//#define MARIO_ANI_FIRE_MAX_SPEED_RIGHT	84
//#define MARIO_ANI_FIRE_MAX_SPEED_LEFT	85
//#define MARIO_ANI_SMALL_MAX_SPEED_RIGHT	86
//#define MARIO_ANI_SMALL_MAX_SPEED_LEFT	87
//#define MARIO_ANI_TAIL_MAX_SPEED_RIGHT	88
//#define MARIO_ANI_TAIL_MAX_SPEED_LEFT	89
//#define	MARIO_ANI_FALLING_LEFT			90
//#define MARIO_ANI_FALLING_RIGHT			91
//#define	MARIO_ANI_FIRE_JUMP_FALL_RIGHT	92
//#define MARIO_ANI_FIRE_JUMP_FALL_LEFT	93
//
//
//#define MARIO_ANI_BIG_IDLE_HOLDING_RIGHT		94	
//#define MARIO_ANI_BIG_IDLE_HOLDING_LEFT			95
//#define MARIO_ANI_SMALL_IDLE_HOLDING_RIGHT		96	
//#define MARIO_ANI_SMALL_IDLE_HOLDING_LEFT		97
//#define MARIO_ANI_TAIL_IDLE_HOLDING_RIGHT		98	
//#define MARIO_ANI_TAIL_IDLE_HOLDING_LEFT		99
//#define MARIO_ANI_FIRE_IDLE_HOLDING_RIGHT		100	
//#define MARIO_ANI_FIRE_IDLE_HOLDING_LEFT		101
//
//
//#define MARIO_GREEN_ANI_BIG_IDLE_RIGHT			102
//#define MARIO_GREEN_ANI_BIG_IDLE_LEFT			103
//#define MARIO_GREEN_ANI_BIG_WALKING_RIGHT		104
//#define MARIO_GREEN_ANI_BIG_WALKING_LEFT		105
//#define MARIO_GREEN_ANI_BIG_JUMPING_RIGHT		106
//#define MARIO_GREEN_ANI_BIG_JUMPING_LEFT		107
//#define MARIO_GREEN_ANI_BIG_HOLDING_IDLE_RIGHT	108
//#define MARIO_GREEN_ANI_BIG_HOLDING_IDLE_LEFT	109
//#define MARIO_GREEN_ANI_BIG_HOLDING_RIGHT		110
//#define MARIO_GREEN_ANI_BIG_HOLDING_LEFT		111
//#define MARIO_GREEN_ANI_BIG_KICKING_RIGHT		112
//#define MARIO_GREEN_ANI_BIG_KICKING_LEFT		113
//#define MARIO_GREEN_ANI_JUMP_FALL_RIGHT			114
//#define MARIO_GREEN_ANI_JUMP_FALL_LEFT			115
//#define MARIO_GREEN_ANI_BIG_RUNNING_RIGHT		116
//#define MARIO_GREEN_ANI_BIG_RUNNING_LEFT		117
//
//#define MARIO_RED_ANI_HITTED					118
//#define MARIO_RED_LOOKING_UP					119
//
//#define MARIO_ANI_DIE							120
//
//#define MARIO_ANI_BIG_PIPE						121
//#define MARIO_ANI_SMALL_PIPE					122
//#define MARIO_ANI_TAIL_PIPE						123
//#define MARIO_ANI_FIRE_PIPE						124
//
//#define MARIO_TRANSFORM_LEFT					125
//#define MARIO_TRANSFORM_RIGHT					126
//
//#define MARIO_SMOKE_TRANSFORM_LEFT				127
//#define MARIO_SMOKE_TRANSFORM_RIGHT				128
//
//#define MARIO_ANI_BIG_JUMP_MAX_POWER_RIGHT			129
//#define MARIO_ANI_BIG_JUMP_MAX_POWER_LEFT			130
//#define MARIO_ANI_SMALL_JUMP_MAX_POWER_RIGHT		131
//#define MARIO_ANI_SMALL_JUMP_MAX_POWER_LEFT		    132
//#define MARIO_ANI_TAIL_JUMP_MAX_POWER_RIGHT			133
//#define MARIO_ANI_TAIL_JUMP_MAX_POWER_LEFT			134
//#define MARIO_ANI_FIRE_JUMP_MAX_POWER_RIGHT			135
//#define MARIO_ANI_FIRE_JUMP_MAX_POWER_LEFT			136
//
//#define MARIO_TYPE_RED			1
//#define MARIO_TYPE_GREEN		2
//
//#define	MARIO_LEVEL_BIG		2
//#define	MARIO_LEVEL_SMALL	1
//#define	MARIO_LEVEL_TAIL	3
//#define	MARIO_LEVEL_FIRE	4
//#define MARIO_BIG_BBOX_WIDTH  15
//#define MARIO_TAIL_BBOX_WIDTH  22
//#define MARIO_BIG_BBOX_HEIGHT 27
//#define MARIO_SMALL_BBOX_HEIGHT_DIFF	10
//
//#define MARIO_SMALL_BBOX_WIDTH  13
//#define MARIO_SMALL_BBOX_HEIGHT 15
//
//#define MARIO_BBOX_HEIGHT_DIFF 12
//
//#define MARIO_UNTOUCHABLE_TIME 1500
//
//#define MARIO_KICKING_TIME 200
//
//#define MARIO_SPINING_TIME 400
//
//#define MARIO_SPEEDUP_TIME 250
//
//#define MARIO_SPEEDDOWN_TIME 400
//
//#define MARIO_TRANSFORM_TIME 1000
//
//#define MARIO_FIRING_TIME	100
//
//#define	MARIO_KEEP_STACK_TIME	3000
//#define	MARIO_MUSHROOM_PUSH_UP	0.0001f
//#define	MARIO_MOVINGHORIZONTALRECTANGLE_PUSH_UP	0.001f
//#define	MARIO_JUMP_LONG_START_TIME	50
//#define	MARIO_MAX_LONG_JUMP_TIME	20
//#define	MARIO_WORLD_END_SCENE_SHOW_TIME	1000
//#define	MARIO_TIME_TO_POINT_TIME	3000
//#define	MARIO_TIME_PICKER_SUBBING_TIME	50
//#define	MARIO_CAL_TOTAL_POINT_TIME	6000
//#define	MARIO_SWITCH_SCENE_TIME	8000
//#define	MARIO_PIPING_DOWN_TIME_LIMIT	2500
//#define	MARIO_PIPING_DOWN_TIME_LIMIT_2	5000
//#define	MARIO_PIPE_UPPING_TIME_LIMIT	3500
//#define	MARIO_PIPE_UPPING_TIME_LIMIT_2	6500
//#define	MARIO_PIPE_UPPING_TIME_LIMIT_2_SMALL	5500
//#define	MARIO_PIPE_UPPING_TIME_LIMIT_2_1_4	4500
//#define	MARIO_PIPE_UPPING_TIME_LIMIT_2_1_4_SMALL	3500
//#define	MARIO_SPINNING_TIME_LIMIT	200
//#define	MARIO_LEFT_RECT_LEGHT	9
//#define	MARIO_TOP_RECT_LEGHT	15
//#define	MARIO_RIGHT_RECT_LEGHT	25
//#define	MARIO_BOTTOM_RECT_LEGHT	8
//#define	MARIO_DIE_TIME_LIMIT	2000
//#define	MARIO_CAM_MOVE_PUSH_X_LEFT	3.0f
//#define	MARIO_MARIO_STATE_IDLE_SPEED	0
//#define	MARIO_PIPING_SPEED	0.01f
//
//
////WORLD_MAP
//
//#define OBJECT_WORLDMAP_TYPE_MARIO				0
//#define OBJECT_WORLDMAP_TYPE_HELP				1
//#define OBJECT_WORLDMAP_TYPE_GOLD_DIGGER			2
//#define OBJECT_WORLDMAP_TYPE_BUSH				3
//#define OBJECT_WORLDMAP_TYPE_NODE				4
//
//#define OBJECT_WORLDMAP_TYPE_HUD_PANEL			5
//#define OBJECT_WORLDMAP_TYPE_MARIO_LUIGI			6
//#define OBJECT_WORLDMAP_TYPE_LIFE				7
//#define OBJECT_WORLDMAP_TYPE_MONEY				8
//#define OBJECT_WORLDMAP_TYPE_SCORE				9
//#define OBJECT_WORLDMAP_TYPE_TIME_PICKER			10
//#define OBJECT_WORLDMAP_TYPE_WORLD				11
//#define OBJECT_WORLDMAP_TYPE_STACK_NORMAL		12
//#define OBJECT_WORLDMAP_TYPE_STACK_MAX			13
//#define OBJECT_WORLDMAP_TYPE_ITEM				14
//#define OBJECT_WORLDMAP_TYPE_STAGE_1				15
//#define OBJECT_WORLDMAP_TYPE_STAGE_2				16
//#define	OBJECT_WORLDMAP_TYPE_NEW_MAP_CAM	47
//
//
////BACKGROUND_STAGE
//#define BACKGROUND_STAGE_STATE_IDLE		0
//#define BACKGROUND_STAGE_STATE_DOWN		100
//#define BACKGROUND_STAGE_STATE_SHAKE	200
//
//
//#define BACKGROUND_STAGE_TYPE_BLACK_ANI		0	
//#define BACKGROUND_STAGE_TYPE_COLOR_ANI		1
//#define BACKGROUND_STAGE_TYPE_FINAL_ANI		2
//
//
//#define BACKGROUND_STAGE_TYPE_BLACK		111
//#define BACKGROUND_STAGE_TYPE_COLOR		222
//#define BACKGROUND_STAGE_TYPE_FINAL		333
//#define	BACKGROUND_STAGE_APPEAR_TIME_LIMIT	2000
//#define	BACKGROUND_STAGE_APPEAR_2_TIME_LIMIT	5600
//#define	BACKGROUND_STAGE_APPEAR_3_TIME_LIMIT	7000
//#define	BACKGROUND_STAGE_SHAKE_TIME_LIMIT	500
//#define	BACKGROUND_STAGE_DOWN_TIME_LIMIT	700
//#define	BACKGROUND_STAGE_IDLE_TIME_LIMIT	1400
//#define	BACKGROUND_STAGE_SHAKE_RAPID	25
//#define	BACKGROUND_STAGE_SHAKE_SPEED_VY	0.2f
//#define	BACKGROUND_STAGE_IDLE_SPEED	0
//#define	BACKGROUND_STAGE_DOWN_SPEED	0.1f
//
////COIN
//#define COIN_BBOX_WIDTH  10
//#define COIN_BBOX_HEIGHT 15
//
//
//#define COIN_STATE_IDLE		0
//#define COIN_STATE_UP		100
//#define COIN_STATE_DOWN		200
//
//#define COIN_NORMAL			222
//#define COIN_CAN_MOVE		333
//
//
//
//#define	COIN_STATE_UP_TIME_UP		300
//#define COIN_STATE_DOWN_TIME_DOWN	300
//
//#define COIN_POSITION_SHOW_SCORE_Y		10
//#define COIN_STATE_IDLE_SPEED			0
//#define COIN_STATE_UP_SPEED				0.2f
//#define COIN_STATE_DOWN_SPEED			0.2f
//
////FIRE FLOWER
//#define FIRE_FLOWER_BBOX_WIDTH		16
//#define FIRE_FLOWER_BBOX_HEIGHT		16
//
//#define FIRE_FLOWER_STATE_IDLE		0
//#define FIRE_FLOWER_STATE_UP		100
//
//
//#define FIRE_FLOWER_STATE_UP_TIME	300		
//#define	FIRE_FLOWER_ORIGIN_POSITION		7000
//#define	FIRE_FLOWER_IDLE_SPEED			0
//#define	FIRE_FLOWER_UP_SPEED			0.05f
//
////GOOMBA
//
//#define GOOMBA_WALKING_SPEED		 0.05f
//#define GOOMBA_GRAVITY				 0.002f
//#define GOOMBA_DIE_DEFLECT_SPEED	 0.5f
//#define GOOMBA_JUMP_SPEED			 0.35f
//
//
//
//#define GOOMBA_NORMAL_BBOX_WIDTH			16
//#define GOOMBA_NORMAL_BBOX_HEIGHT			15
//#define GOOMBA_RED_FLY_BBOX_WIDTH			20
//#define GOOMBA_RED_FLY_BBOX_HEIGHT			24
//#define GOOMBA_RED_LOSE_WINGS_BBOX_WIDTH	20
//#define GOOMBA_RED_LOSE_WINGS_BBOX_HEIGHT	19
//
//
//#define GOOMBA_STATE_WALKING		100
//#define GOOMBA_STATE_DIE			200
//#define GOOMBA_STATE_DISAPPEAR		300
//#define GOOMBA_STATE_DIE_2	400
//#define GOOMBA_STATE_RED_LOSE_WINGS 500
//#define GOOMBA_STATE_IDLE			600
//#define GOOMBA_STATE_GEARING		700
//#define GOOMBA_STATE_FLYING			800
//
//
//
//#define GOOMBA_NORMAL_ANI_WALKING		0
//#define GOOMBA_NORMAL_ANI_DIE			1
//#define GOOMBA_RED_FLY_ANI_WALKING		2
//#define GOOMBA_RED_FLY_ANI_DIE			3	
//#define GOOMBA_RED_FLY_ANI_LOSE_WINGS	4
//#define GOOMBA_NORMAL_ANI_IDLE			5
//#define GOOMBA_RED_FLY_ANI_DIE_BY_KICK	6
//#define GOOMBA_NORMAL_ANI_DIE_BY_KICK	7
//#define GOOMBA_RED_ANI_GEARING			8
//#define GOOMBA_RED_ANI_FLYING			9
//
//#define GOOMBA_NORMAL	888
//#define GOOMBA_RED_FLY	999
//
//#define GOOMBA_TIME_JUMPING		900
//
//#define GOOMBA_NX						1
//#define GOOMBA_STATE_DIE_BONUS_TOP		7
//#define GOOMBA_STATE_WALKING_BONUS_BOTTOM	19
//#define GOOMBA_STATE_RED_LOSE_WINGS_BONUS_TOP	7
//#define GOOMBA_TIME_SWITCH_STATE	1000
//#define GOOMBA_SWITCH_STATE_MINUS_Y		5
//#define GOOMBA_STATE_GEARING_JUMPING_START  400
//#define GOOMBA_JUMP_START_ORIGIN_VALUE	0
//#define GOOMBA_CONTROL_JUMPTIME_FIRST	0
//#define GOOMBA_CONTROL_JUMPTIME_SECOND	1
//#define GOOMBA_JUMP_VY					0.2f
//#define GOOMBA_FLYING_VY				0.4f
//#define GOOMBA_TIME_RUNNING_INTRO_SCENE		200
//#define GOOMBA_TIME_RUNNING_INTRO_SCENE_ORIGIN_VALUE 0
//#define GOOMBA_DYING_TIME_ORIGIN_VALUE			0
//#define GOOMBA_DYING_TIME						500
//#define GOOMBA_STATE_FLYING_SWITCHING_STATE_TIME	500
//#define GOOMBA_STATE_DIE_BY_KICK_VX				0.1f
//#define GOOMBA_ORIGIN_SPEED						0
//
////#======= HIT EFFECT
//#define HIT_EFFECT_STATE_IDLE	0
//
//#define HIT_EFFECT_TURN_TAIL			100
//#define HIT_EFFECT_FIRE_BULLET			200	
//
//
//#define HIT_EFFECT_TURN_TAIL_ANI_RIGHT			0
//#define HIT_EFFECT_TURN_TAIL_ANI_LEFT			1
//#define HIT_EFFECT_ANI_FIRE_BULLET				2
//
//
//
//#define HIT_EFFECT_TURN_TAIL_BONUS_X		5
//#define HIT_EFFECT_TURN_TAIL_BONUS_Y		10
//#define HIT_EFFECT_TURN_TAIL_TIME_SHOWING	250
//#define HIT_EFFECT_TURN_TAIL_ORIGIN_POSITION	7000
//#define TIMING_START_ORIGIN_VALUE		0
//
//#define HIT_EFFECT_FIRE_BULLET_BONUS_X		5
//#define HIT_EFFECT_FIRE_BULLET_BONUS_Y		10
//#define HIT_EFFECT_FIRE_BULLET_TIME_SHOWING	250
//#define HIT_EFFECT_STATE_IDLE_SPEED			0
////#define	A
//class define
//{
//};
//
