#pragma once
//GENERAL
#define STORING_LOCATION_X		-99999
#define STORING_LOCATION_Y		-99999
//PLAYER

#define TANKWHEEL_STATE_DIE 0
#define TANKWHEEL_BBOX_WIDTH 10
#define TANKWHEEL_BBOX_HEIGHT 10

#define TANKWHEEL_WHEEL_DISTANT_X_1 1
#define TANKWHEEL_WHEEL_DISTANT_X_2 17
#define TANKWHEEL_WHEEL_DISTANT_Y 10

#define TURRET_ANI_IDLE_LEFT 1
#define TURRET_ANI_IDLE_RIGHT 0
#define TURRET_DISTANT_X 0
#define TURRET_DISTANT_Y 0

#define BODY_DISTANT_X 9
#define BODY_DISTANT_Y 9

#define TANKWHEEL_LEFT_WHEEL 0
#define TANKWHEEL_RIGHT_WHEEL 1
#define TANKWHEEL_TURRET 2

#define WHEELING_ANI_RIGHT 0
#define WHEELING_ANI_LEFT 1
#define WHEELING_ANI_IDLE 2

#define TANKBODY_ANI_IDLE 0

#define TURRET_ANI_IDLE_LEFT 1
#define TURRET_ANI_IDLE_RIGHT 0

#define TANKWHEEL_TURRET_DISTANT_X 9
#define TANKWHEEL_TURRET_DISTANT_Y 10


#define SOPHIA_WALKING_SPEED		0.15f
//0.1f
#define SOPHIA_JUMP_SPEED_Y		0.5f
#define SOPHIA_JUMP_DEFLECT_SPEED 0.2f
#define SOPHIA_GRAVITY			0.002f
#define SOPHIA_DIE_DEFLECT_SPEED	 0.5f

#define SOPHIA_STATE_IDLE			0
#define SOPHIA_STATE_WALKING_RIGHT	100
#define SOPHIA_STATE_WALKING_LEFT	200
#define SOPHIA_STATE_WALKING_UP	500
#define SOPHIA_STATE_WALKING_DOWN	600
#define SOPHIA_STATE_JUMP			300
#define SOPHIA_STATE_DIE				400

#define SOPHIA_ANI_BIG_IDLE_RIGHT		0
#define SOPHIA_ANI_BIG_IDLE_LEFT			1
#define SOPHIA_ANI_SMALL_IDLE_RIGHT		2
#define SOPHIA_ANI_SMALL_IDLE_LEFT			3

#define SOPHIA_ANI_BIG_WALKING_RIGHT			4
#define SOPHIA_ANI_BIG_WALKING_LEFT			5
#define SOPHIA_ANI_SMALL_WALKING_RIGHT		6
#define SOPHIA_ANI_SMALL_WALKING_LEFT		7

#define SOPHIA_ANI_DIE				8

#define	SOPHIA_LEVEL_SMALL	1
#define	SOPHIA_LEVEL_BIG		2

#define SOPHIA_BIG_BBOX_WIDTH  26
#define SOPHIA_BIG_BBOX_HEIGHT 18


#define SOPHIA_SMALL_BBOX_WIDTH  13
#define SOPHIA_SMALL_BBOX_HEIGHT 15

#define SOPHIA_UNTOUCHABLE_TIME 5000
#define SOPHIA_FIRING_DELAY_TIME 500

/////////////
